name: $(GITVERSION_FullSemVer)

pool:
  vmImage: vs2017-win2016
variables:
  BuildConfiguration: 'Release'
  GitVersion.SemVer: ''

steps:
- task: UseGitVersion@5
  displayName: GitVersion
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.sln'
    feedsToUse: config
    nugetConfigPath: nuget.config

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.sln'
    configuration: '$(BuildConfiguration)'
    arguments: '--no-restore'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'test/**/*.UnitTests/*.csproj'
    configuration: '$(BuildConfiguration)'
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack release'
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     **/bin/$(BuildConfiguration)/**
     docs/**
     *.nupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
